# Generated by Django 5.0 on 2024-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='pan',
            field=models.CharField(default='', max_length=10),
        ),
    ]
