# Generated by Django 5.0 on 2024-03-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bills_billitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitems',
            name='price',
        ),
        migrations.AddField(
            model_name='billitems',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.items'),
            preserve_default=False,
        ),
    ]
