# Generated by Django 5.0 on 2024-03-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_billitems_price_billitems_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitems',
            old_name='bill_id',
            new_name='bill',
        ),
    ]
