# Generated by Django 5.0 on 2024-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_bill_id_billitems_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.CharField(choices=[('regular', 'regular'), ('cancelled', 'cancelled')], default='regular', max_length=10),
        ),
    ]
