# Generated by Django 5.0 on 2024-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bills_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
