# Generated by Django 5.0 on 2024-05-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_items_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bill_no',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='bills',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bills',
            name='invoice_date',
            field=models.DateTimeField(),
        ),
    ]
