# Generated by Django 5.0 on 2024-05-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bills_bill_no_bills_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_no',
            field=models.IntegerField(default=1),
        ),
    ]
